name: Build and Deploy Pelican Site

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican markdown

      - name: Build Pelican site
        run: pelican content -o output -s pelicanconf.py
      - name: Setup git
        run: |
          git config --global user.name "coderga"
          git config --global user.email "quanggiatrang@gmail.com"
      - name: Deploy to GitHub Pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd output
          git init
          git add .
          git commit -m "Deploy Pelican site"
          git remote set-url origin https://coderga@github.com/coderga/my-blog.git
          git branch -M gh-pages
          git push --set-upstream gh-pages

#          git push -f origin gh-pages

#git remote add origin https://github.com/coderga/my-blog.git
