name: Build and Deploy Pelican Site to GitHub Pages

on:
  push:
    branches:
      - main # Thay thế 'main' bằng tên nhánh chính của bạn nếu khác

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true # Nếu trang web của bạn sử dụng submodules

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x" # Sử dụng phiên bản Python phù hợp với dự án của bạn

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican ghp-import

      - name: Build the Pelican site
        run: |
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./output
          keep_files: false
          user_name: "github-actions[bot]"
          user_email: "github-actions[bot]@users.noreply.github.com"
          commit_message: "Deploy Pelican site to GitHub Pages"
