name: Build and Deploy Pelican Blog

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pelican markdown
      - name: List directory contents
        run: ls -la themes
      - name: Build Pelican site
        run: pelican content -o output -s pelicanconf.py

      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v3
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     publish_branch: gh-pages
      #     publish_dir: output
      - name: Deploy to GitHub Pages
        run: |
          cd output
          git init
          git remote add origin https://github.com/coderga/my-blog.git
          git checkout -B gh-pages
          git add .
          git commit -m "Deploy Pelican site"
          git push -f origin gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
